"""Component base classes, registration decorators, and built-in components."""

from training_framework.components.base import (
    Component,
    Hook,
    IterationHook,
    LifecycleHook,
    Resource,
    SessionHook,
    Stateful,
    StatefulIterationHook,
    StatefulLifecycleHook,
    StatefulLifeCycleHook,
    StatefulResource,
    StatefulSessionHook,
    StatefulStep,
    Step,
)
from training_framework.components.registry import (
    ANALYSIS_SESSION_TYPE,
    TRAINING_SESSION_TYPE,
    ComponentAliases,
    component_registry,
    format_execution_graph,
    hook,
    requires_hook,
    requires_resource,
    requires_step,
    resource,
    step,
    topological_sort_of_components,
    wraps,
)

__all__ = [
    "ANALYSIS_SESSION_TYPE",
    "TRAINING_SESSION_TYPE",
    "Component",
    "ComponentAliases",
    "Hook",
    "IterationHook",
    "LifecycleHook",
    "Resource",
    "SessionHook",
    "Stateful",
    "StatefulIterationHook",
    "StatefulLifecycleHook",
    "StatefulLifeCycleHook",
    "StatefulResource",
    "StatefulSessionHook",
    "StatefulStep",
    "Step",
    "component_registry",
    "format_execution_graph",
    "hook",
    "requires_hook",
    "requires_resource",
    "requires_step",
    "resource",
    "step",
    "topological_sort_of_components",
    "wraps",
]

from training_framework.components import builtin as builtin
